default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: vexuf24_development

test:
  <<: *default
  database: vexuf24_test

production:
  <<: *default
  database: vexuf24_production
  username: vexuf24_db_mastermind
  password: <%= ENV["VEXUF24_DATABASE_PASSWORD"] %>
  host: dpg-co05cmv79t8c73d8pvs0-a
