name: 'CI'
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    services:
      postgres:
        image: postgres:15-alpine
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
      - name: Rubocop
        run: bundle exec rubocop --parallel
      - name: Setup database
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
        run: |
          cp config/database.ci.yml config/database.yml
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Display tasks
        run: rake --tasks
      - name: Run Ruby tests
        run: bin/rake --trace
      - name: Run JavaScript tests
        run: yarn test
      - name: Run linting
        run: yarn lint
      - name: Run TypeScript checks
        run: yarn ts:check
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
      - name: Security audit application code
        run: bundle exec brakeman -q -w2
      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results
      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: log
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tmp/screenshots
